### ISSUE TITLE
requirement:MacOS

### ISSUE THREAD

**Issue by AjianYo** [botbahlul/autosrt#1]
How should MacOS use this tool ?

**Comment by botbahlul** [comment]
I've tried on Windows, Linux Debian 9, and Android via Termux app, but haven't tried this on Mac

But you can try to install pip first :
https://www.groovypost.com/howto/install-pip-on-a-mac/#:~:text=To%20install%20PIP%20using%20ensurepip,instructions%20to%20complete%20this%20process.

after that try to install autosrt with pip :
```
pip install --upgrade autosrt
```
